# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
pandoc_version: 1.16
language: python
python:
  - "3.4"
sudo: false
addons:
  apt:
    packages:
    - pandoc
install:
  - pip install codecov
script:
    python3 ./tests/test_basic.py
