# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
sudo: false
install:
  - pip install --user codecov
after_success:
  - codecov
script: make test    
